### ISSUE TITLE
Unable to find "Fuse Ignite (OCP environment)" image

### ISSUE THREAD

**Issue by sigreen** [RedHatWorkshops/fusev7-workshop#13]
I've logged into the OpenTLC lab environment as stipulated by the setup instructions.  Step 6 specifies I must select the "Fuse Ignite (OCP environment)" image, but unfortunately the image does not exist.  Is this an issue with my account, or do I need to select another image?

**Comment by honghuac** [comment]
It does now, please try the updated [lab](https://github.com/RedHatWorkshops/fusev7-workshop/blob/master/labs/00_setup_n_intro/01_1_ignite_environment_setup_Lab.adoc) again. Thanks @sigreen

**Comment by honghuac** [comment]
Closed
