### ISSUE TITLE
New Lab Use Case 4: Camel EIPs as technical / connector extensions 

### ISSUE THREAD

**Issue by honghuac** [RedHatWorkshops/fusev7-workshop#6]
Use case involving the "re-use" of Camel EIPs (implemented as Java Apps) as technical extensions.
Lab will see these technical extensions setup and used as Camel EIPs within Fuse Ignite integrations.
Use Aggregation and Splitter EIPs - cause they are mighty popular.

Recommend this Use Case (4) be combined with Use Case 1 (POJO technical extension)

**Comment by honghuac** [comment]
Use extensions from this library https://github.com/syndesisio/syndesis-extensions

**Comment by weimeilin79** [comment]
Aggression and spilt

**Comment by honghuac** [comment]
I have prepared an [architecture](https://docs.google.com/spreadsheets/d/1tCIGzt_rr9wD2A7Tn331y-AFAj0pj1537dJhK-9PlCk) of the Camel Routes with respective EIP->Extension mappings.

**Comment by honghuac** [comment]
Closed.
